import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import WaveButton from '../components/waveButton.jsx'

export default function Home() {
  return (
    <div className="bg-gradient-to-bl from-blue-400 via-blue-300 to-green-400 h-screen">
      <Head>
        <title>Jake&#39;s WavePortal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
      <h1 id="title" className="text-center">whalecum to wave counter</h1>
      <h2 id="bio" className="text-center">please wave to me ser</h2>
      <WaveButton className=""></WaveButton>
      {/* <button>Wave</button> */}
    </div>
  )
}
